### PR TITLE
LVUIDF-0: added extended description of project purpose.

### PR DESCRIPTION
**Pull request by izagor**
https://ssu-jira.softserveinc.com/browse/LVUIDF-0

Added this PR as example to show convention how to work with the code in this project.

To review:
- [x] @rtriska
- [x] @vyshnevska

Optional:
- [x] @irynar 

To merge:
- [x] @izagor

### CODE REVIEW

**Comment by izagor** [comment]
Test run is not needed until we have tests and set up CI for this repository.

**Comment by irynar** [comment]
+1

**Comment by rtriska** [comment]
looks good to me :+1:

**Comment by izagor** [comment]
Changes are fine :+1:

**Pull request merged**
